; =========================================================
; PlatformIO Project Configuration File
; =========================================================
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor baud rate
monitor_speed = 115200

; Use huge_app.csv to allocate more flash memory for OTA updates
board_build.partitions = huge_app.csv  

; ডায়নামিক ভেরিয়েবল ইনজেক্ট করার স্ক্রিপ্ট
extra_scripts = pre:scripts/apply_env.py

; External library dependencies
lib_deps =
    adafruit/Adafruit BME680 Library @ ^2.0.2
    adafruit/Adafruit Unified Sensor @ ^1.1.14