; =========================================================
; PlatformIO Project Configuration File
; =========================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor baud rate
monitor_speed = 115200

; Use huge_app.csv to allocate more flash memory for OTA updates
board_build.partitions = huge_app.csv  

; External library dependencies
lib_deps =
    adafruit/Adafruit BME680 Library @ ^2.0.2
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    ; Note: QuectelEC200U should be placed in the local 'lib' folder